# Generated by Django 4.2.7 on 2024-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
