# Generated by Django 4.2.7 on 2024-03-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_users_book_user'),
        ('author', '0005_alter_author_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='authors_books', to='book.book'),
            preserve_default=False,
        ),
    ]
