# Generated by Django 4.2.7 on 2024-03-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_remove_author_books_author_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
