# Generated by Django 4.2.7 on 2024-03-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appuser_books_appuser_read_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='books',
        ),
    ]
