# Generated by Django 4.2.7 on 2024-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_users'),
        ('user', '0003_remove_appuser_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='read_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_books', to='book.book'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='want_to_read',
            field=models.ManyToManyField(blank=True, null=True, related_name='want_to_read', to='book.book'),
        ),
    ]
