# Generated by Django 4.2.7 on 2024-03-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_users_book_user'),
        ('user', '0004_alter_appuser_read_books_alter_appuser_want_to_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='read_books',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='want_to_read',
        ),
        migrations.AddField(
            model_name='appuser',
            name='want_to_read',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.book'),
            preserve_default=False,
        ),
    ]
