# Generated by Django 4.2.7 on 2024-03-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_users_book_user'),
        ('user', '0006_rename_want_to_read_appuser_booksuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='booksUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
