# Generated by Django 4.2.7 on 2024-03-27 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTheBook', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('users', models.ManyToManyField(related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
