# Generated by Django 4.2.7 on 2024-03-27 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
