# Generated by Django 4.2.7 on 2024-03-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
